import {
  connectDatabase,
  insertDocument,
  getAllDocuments,
} from "../../../helpers/db-utils";

export default async function handler(req, res) {
  const { eventId } = req.query;
  let client;

  try {
    client = await connectDatabase();
  } catch (err) {
    res.status(500).json({ message: err.message });
    return;
  }

  if (req.method === "POST") {
    const { email, name, text } = req.body;

    const validEmail = email.includes("@");
    const validName = name || !name.trim() === "";
    const validText = text || !text.trim() === "";

    if (!validEmail || !validName || !validText) {
      client.close();
      res.status(422).json({ message: "Invalid input" });
      return;
    }

    const newComment = {
      email,
      name,
      text,
      eventId,
    };

    // (client, collection, document)
    let result;
    try {
      result = await insertDocument(client, "comments", newComment);
      newComment._id = result.insertedId;
      res
        .status(201)
        .json({ message: "New comment added ", comment: newComment });
    } catch (err) {
      res.status(500).json({ message: err.message });
    }

    // set the comment id to the id generated by mongo, in case we need it before the page is requested again
  }

  if (req.method === "GET") {
    try {
      const fetchedComments = await getAllDocuments(client, "comments", {
        _id: -1,
      });
      res.status(201).json({ comments: fetchedComments });
    } catch (err) {
      res.status(500).json({ message: err.message });
    }
  }
  client.close();
}
